<?php

namespace App\Services;

use App\Models\Router;
use App\Models\Package;
use App\Models\HotspotSession;
use Illuminate\Support\Facades\Log;
use RouterOS\Client;
use RouterOS\Query;
use Exception;

/**
 * MikroTik router service.
 *
 * User/profile creation via the MikroTik API is the primary flow for the
 * captive portal.
 */
class MikroTikService
{

    /**
     * Create hotspot user and profile on MikroTik router using the
     * authorization's hotspot credentials. This is the API-only flow —
     * no FreeRADIUS roundtrip is required.
     */
    public function createHotspotSession(HotspotSession $session): bool
    {
        try {
            $router = $session->package->router;

            if (!$router) {
                Log::warning('No router found for session', ['session_id' => $session->session_id]);
                return false;
            }

            $client = $this->connectToRouter($router);

            if (!$client) {
                return false;
            }

            // Create / update user profile for the package
            $profileName = $this->createOrUpdateUserProfile($client, $session);

            // Use the credentials already generated by HotspotAuthorizationService
            $authorization = $session->authorization;
            $username = $authorization?->hotspot_username
                ?? $session->mikrotik_username
                ?? $session->username
                ?? $session->session_id;

            $password = $authorization?->hotspotPassword()
                ?? $this->generatePassword();

            $this->createUser($client, $username, $password, $profileName, $session);

            // Update session with credentials
            $session->update([
                'mikrotik_username' => $username,
                'mikrotik_password' => $password,
                'mikrotik_profile' => $profileName,
            ]);

            Log::info('Hotspot user created on MikroTik via API', [
                'session_id' => $session->session_id,
                'router_id' => $router->id,
                'username' => $username,
                'profile' => $profileName,
            ]);

            return true;

        } catch (Exception $e) {
            Log::error('Failed to create hotspot session on MikroTik', [
                'session_id' => $session->session_id,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    /**
     * Disconnect user from MikroTik hotspot.
     *
     * Removes the active hotspot session and cookie so the user goes offline,
     * but only removes the hotspot user entry if the session has no remaining
     * time. Keeping the user entry allows a reconnect while the session is
     * still valid.
     */
    public function disconnectUser(HotspotSession $session): bool
    {
        try {
            $router = $session->package->router;
            if (!$router) {
                Log::warning('No router found for session', ['session_id' => $session->session_id]);
                return false;
            }
            $client = $this->connectToRouter($router);
            if (!$client) {
                return false;
            }
            $this->removeActiveSessions($client, $session);
            $this->removeHotspotCookie($client, $session);

            // Only delete the hotspot user entry if time has run out. If the
            // session is still valid (status disconnected but expires_at is
            // in the future), keep the user so the device can reconnect.
            $now = now();
            $expiresAt = $session->expires_at;
            $createdAt = $session->created_at;
            $stillValid = $expiresAt && $expiresAt > $now;
            $recentlyCreated = $createdAt && $createdAt->diffInSeconds($now) < 300;

            if ($recentlyCreated && $stillValid) {
                Log::info('User disconnected from MikroTik but kept hotspot user (recently created, still valid)', [
                    'session_id' => $session->session_id,
                    'router_id' => $router->id,
                    'created_at' => $createdAt->toDateTimeString(),
                    'expires_at' => $expiresAt->toDateTimeString(),
                ]);
            } elseif (!$stillValid) {
                $this->removeUser($client, $session);
            } else {
                Log::info('User disconnected from MikroTik but kept hotspot user (still valid)', [
                    'session_id' => $session->session_id,
                    'router_id' => $router->id,
                    'expires_at' => $expiresAt->toDateTimeString(),
                ]);
            }

            Log::info('User disconnected from MikroTik', [
                'session_id' => $session->session_id,
                'router_id' => $router->id,
                'removed_user' => !$stillValid && !($recentlyCreated && $stillValid),
                'status' => $session->status,
                'expires_at' => $expiresAt ? $expiresAt->toDateTimeString() : null,
            ]);
            return true;
        } catch (Exception $e) {
            Log::error('Failed to disconnect user from MikroTik', [
                'session_id' => $session->session_id,
                'error' => $e->getMessage()
            ]);
            return false;
        }
    }

    /**
     * Disconnect a PPPoE user from MikroTik router
     */
    public function disconnectPppoeUser(HotspotSession $session): bool
    {
        try {
            $router = $session->package->router;

            if (!$router) {
                return false;
            }

            $client = $this->connectToRouter($router);

            if (!$client) {
                return false;
            }

            $username = $session->mikrotik_username ?: $session->username ?: $session->session_id;

            // Find and remove active PPPoE connection
            $query = new Query('/ppp/active/print');
            $query->where('name', $username);
            $activeConns = $client->query($query)->read();

            foreach ($activeConns as $conn) {
                if (isset($conn['.id'])) {
                    $removeQuery = (new Query('/ppp/active/remove'))
                        ->equal('.id', $conn['.id']);
                    $client->query($removeQuery)->read();
                }
            }

            // Remove PPPoE secret
            $secretQuery = new Query('/ppp/secret/print');
            $secretQuery->where('name', $username);
            $secrets = $client->query($secretQuery)->read();

            foreach ($secrets as $secret) {
                if (isset($secret['.id'])) {
                    $removeQuery = (new Query('/ppp/secret/remove'))
                        ->equal('.id', $secret['.id']);
                    $client->query($removeQuery)->read();
                }
            }

            Log::info('PPPoE user disconnected from MikroTik', [
                'session_id' => $session->session_id,
                'username' => $username,
                'router_id' => $router->id,
            ]);

            return true;

        } catch (Exception $e) {
            Log::error('Failed to disconnect PPPoE user', [
                'session_id' => $session->session_id,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    /**
     * Connect to MikroTik router
     * Returns null on failure for safe error handling
     */
    public function connectToRouter(Router $router, bool $throw = false): ?Client
    {
        try {
            $host = !empty($router->ip_address) ? $router->ip_address : $router->ip;
            $client = new Client([
                'host' => $host,
                'user' => $router->username,
                'pass' => $router->password ?? '',
                'port' => (int) ($router->api_port ?? 8728),
                'timeout' => 5,
                'attempts' => 1,
                'delay' => 0,
            ]);
            
            // Test connection with a simple query and capture router identity
            $identityQuery = new Query('/system/identity/print');
            $identity = $client->query($identityQuery)->read();
            $routerName = $identity[0]['name'] ?? 'unknown';

            Log::info('Connected to MikroTik router', [
                'router_id' => $router->id,
                'ip' => $host,
                'identity' => $routerName,
            ]);

            return $client;
            
        } catch (Exception $e) {
            Log::error('Failed to connect to MikroTik router', [
                'router_id' => $router->id,
                'ip' => $router->ip_address ?? $router->ip,
                'error' => $e->getMessage()
            ]);
            
            if ($throw) {
                throw $e;
            }
            
            return null;
        }
    }


    /**
     * Test connection to router with detailed diagnostics
     */
    public function testConnection(Router $router): array
    {
        $ip = $router->ip_address ?? $router->ip;
        $apiPort = (int) ($router->api_port ?? 8728);

        // Test API port connectivity
        $apiPortStatus = $this->testPort($ip, $apiPort);
        $apiPortOpen = stripos($apiPortStatus, 'open') !== false;
        
        // Step 2: Test API authentication
        try {
            $client = $this->connectToRouter($router, true);
            
            // Try to get system resource info to verify connection
            $query = new Query('/system/resource/print');
            $response = $client->query($query)->read();
            
            // If API connection succeeds, mark API port as open regardless of port test
            $apiPortOpen = true;
            
            return [
                'success' => true,
                'message' => 'Connection successful',
                'data' => $response,
                'diagnostics' => [
                    'api_port' => $apiPortOpen,
                ]
            ];
        } catch (Exception $exception) {
            return [
                'success' => false,
                'message' => $this->getDetailedErrorMessage($exception),
                'data' => null,
                'diagnostics' => [
                    'api_port' => $apiPortOpen,
                ]
            ];
        }
    }

    /**
     * Test basic connectivity using socket
     */
    private function testPing(string $ip, int $port = 80): string
    {
        // Use socket connection as a ping alternative
        $connection = @fsockopen($ip, $port, $errno, $errstr, 3);
        
        if ($connection) {
            fclose($connection);
            return 'Basic connectivity successful';
        } else {
            // Try ICMP ping if available
            if (function_exists('exec') && !in_array('exec', explode(',', ini_get('disable_functions')))) {
                $command = "ping -n 1 -w 3000 $ip 2>&1";
                exec($command, $output, $return_code);
                $output_string = implode(' ', $output);
                
                if ($return_code === 0 && (strpos($output_string, 'TTL=') !== false || strpos($output_string, 'time=') !== false)) {
                    return 'Ping successful';
                }
            }
            
            return 'Host unreachable - Check IP address and network connectivity';
        }
    }

    /**
     * Test port connectivity
     */
    private function testPort(string $ip, int $port): string
    {
        $connection = @fsockopen($ip, $port, $errno, $errstr, 2);
        
        if ($connection) {
            fclose($connection);
            return "Port $port is open and accepting connections";
        } else {
            if ($errno == 111) {
                return "Port $port is closed - Connection refused";
            } elseif ($errno == 110) {
                return "Port $port connection timed out";
            } elseif ($errno == 0) {
                return "Port $port is not accessible - No error but connection failed";
            } else {
                return "Port $port is not accessible (Error: $errno - $errstr)";
            }
        }
    }

    /**
     * Get detailed error message based on exception
     */
    private function getDetailedErrorMessage(Exception $exception): string
    {
        $message = $exception->getMessage();
        
        if (stripos($message, 'Connection refused') !== false) {
            return 'Connection refused - MikroTik API service may be disabled or the API port is blocked';
        } elseif (stripos($message, 'Connection timed out') !== false || stripos($message, 'A connection attempt failed') !== false) {
            return 'Connection timed out - Router not responding or firewall blocking connection';
        } elseif (stripos($message, 'No route to host') !== false) {
            return 'No route to host - Check network connectivity and router IP address';
        } elseif (stripos($message, 'invalid user name or password') !== false || stripos($message, 'cannot log in') !== false) {
            return 'Authentication failed - Invalid username, password, or user lacks API access';
        } elseif (stripos($message, 'Socket timeout reached') !== false) {
            return 'Socket read timeout - Router is too slow or the API response was interrupted';
        } elseif (stripos($message, 'Unable to establish socket session') !== false) {
            return 'Unable to establish socket session - Check that the MikroTik API service is enabled and reachable';
        } else {
            return "Connection failed: $message";
        }
    }

    /**
     * Get system information
     */
    public function getSystemInfo(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);
            
            if (!$client) {
                return ['success' => false, 'message' => 'Failed to connect to router'];
            }

            // Fetch router system resources (board, uptime, version, memory)
            $query = new Query('/system/resource/print');
            $response = $client->query($query)->read();
            
            if (!empty($response)) {
                return [
                    'success' => true,
                    'data' => $response[0] ?? []
                ];
            }
            
            return ['success' => false, 'message' => 'No system info received'];
        } catch (Exception $exception) {
            return ['success' => false, 'message' => $exception->getMessage()];
        }
    }

    /**
     * Get interface information
     */
    public function getInterfaces(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);
            
            if (!$client) {
                return ['success' => false, 'message' => 'Failed to connect to router'];
            }

            // Fetch all network interfaces and their current configuration
            $query = new Query('/interface/print');
            $response = $client->query($query)->read();
            
            return [
                'success' => true,
                'data' => $response
            ];
        } catch (Exception $exception) {
            return ['success' => false, 'message' => $exception->getMessage()];
        }
    }


    /**
     * Create or update user profile for the package associated with a session.
     */
    protected function createOrUpdateUserProfile(Client $client, HotspotSession $session): string
    {
        return $this->syncPackageProfile($client, $session->package);
    }

    /**
     * Create or update a hotspot user profile for a package on the router.
     */
    protected function syncPackageProfile(Client $client, Package $package): string
    {
        $profileName = 'pkg_' . $package->id . '_' . str_replace(' ', '_', strtolower($package->name));

        try {
            $query = (new Query('/ip/hotspot/user/profile/print'))
                ->where('name', $profileName);

            $existingProfiles = $client->query($query)->read();

            if (empty($existingProfiles)) {
                $this->createUserProfile($client, $profileName, $package);
            } else {
                $this->updateUserProfile($client, $profileName, $package, $existingProfiles[0]['.id']);
            }

            return $profileName;
        } catch (Exception $e) {
            Log::error('Failed to create/update user profile', [
                'profile_name' => $profileName,
                'package_id' => $package->id,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    /**
     * Create user profile
     */
    protected function createUserProfile(Client $client, string $profileName, $package): void
    {
        $profileData = [
            'name' => $profileName,
            'session-timeout' => $this->formatSessionTimeout($package),
            'idle-timeout' => $this->formatSessionTimeout($package),
            'keepalive-timeout' => '00:02:00',
            'status-autorefresh' => '00:01:00',
        ];

        $rateLimit = $this->formatRateLimit($package);
        if ($rateLimit) {
            $profileData['rate-limit'] = $rateLimit;
        }

        Log::info('Creating hotspot user profile on router', [
            'profile_name' => $profileName,
            'package_id' => $package->id,
            'rate_limit' => $rateLimit,
        ]);

        $sharedUsers = $this->formatSharedUsers($package->shared_users ?? null);
        if ($sharedUsers) {
            $profileData['shared-users'] = $sharedUsers;
        }

        $query = new Query('/ip/hotspot/user/profile/add');
        foreach ($profileData as $key => $value) {
            $query->equal($key, $value);
        }

        $addResponse = $client->query($query)->read();

        // Check for !trap error in the response (RouterOS returns traps without throwing)
        if (isset($addResponse['after']['message'])) {
            throw new Exception("Router rejected profile {$profileName}: " . $addResponse['after']['message']);
        }

        // Verify the profile actually exists on the router
        $verifyQuery = (new Query('/ip/hotspot/user/profile/print'))->where('name', $profileName);
        $verify = $client->query($verifyQuery)->read();

        if (empty($verify)) {
            throw new Exception("Profile creation failed: profile {$profileName} was not found after creation.");
        }

        Log::info('Created hotspot user profile', [
            'profile_name' => $profileName,
            'package_id' => $package->id,
            'profile_id' => $verify[0]['.id'] ?? null,
        ]);
    }

    /**
     * Update existing user profile
     */
    protected function updateUserProfile(Client $client, string $profileName, $package, string $profileId): void
    {
        $profileData = [
            'session-timeout' => $this->formatSessionTimeout($package),
            'idle-timeout' => $this->formatSessionTimeout($package),
        ];

        $rateLimit = $this->formatRateLimit($package);
        if ($rateLimit) {
            $profileData['rate-limit'] = $rateLimit;
        }

        $sharedUsers = $this->formatSharedUsers($package->shared_users ?? null);
        if ($sharedUsers) {
            $profileData['shared-users'] = $sharedUsers;
        }

        $query = new Query('/ip/hotspot/user/profile/set');
        $query->equal('.id', $profileId);

        foreach ($profileData as $key => $value) {
            $query->equal($key, $value);
        }

        $updateResponse = $client->query($query)->read();

        if (isset($updateResponse['after']['message'])) {
            throw new Exception("Router rejected profile update {$profileName}: " . $updateResponse['after']['message']);
        }

        Log::info('Updated hotspot user profile', [
            'profile_name' => $profileName,
            'package_id' => $package->id
        ]);
    }

    /**
     * Delete a package's hotspot user profile and any hotspot users tied to it
     * from the router. This should only be called when the package has no
     * active sessions in the app, so we do not disconnect online users.
     */
    public function deletePackageProfile(Router $router, Package $package): array
    {
        $profileName = 'pkg_' . $package->id . '_' . str_replace(' ', '_', strtolower($package->name));

        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return [
                    'success' => false,
                    'message' => 'Could not connect to router',
                ];
            }

            // Remove hotspot users assigned to this profile
            $userQuery = (new Query('/ip/hotspot/user/print'))->where('profile', $profileName);
            $users = $client->query($userQuery)->read();
            $removedUsers = 0;

            foreach ($users as $user) {
                if (isset($user['.id'])) {
                    $removeQuery = (new Query('/ip/hotspot/user/remove'))->equal('.id', $user['.id']);
                    $client->query($removeQuery)->read();
                    $removedUsers++;
                }
            }

            // Remove the profile itself
            $profileQuery = (new Query('/ip/hotspot/user/profile/print'))->where('name', $profileName);
            $profiles = $client->query($profileQuery)->read();
            $removedProfiles = 0;

            foreach ($profiles as $profile) {
                if (isset($profile['.id'])) {
                    $removeQuery = (new Query('/ip/hotspot/user/profile/remove'))->equal('.id', $profile['.id']);
                    $client->query($removeQuery)->read();
                    $removedProfiles++;
                }
            }

            Log::info('Deleted package profile from router', [
                'router_id' => $router->id,
                'package_id' => $package->id,
                'profile_name' => $profileName,
                'removed_users' => $removedUsers,
                'removed_profiles' => $removedProfiles,
            ]);

            return [
                'success' => true,
                'message' => "Removed {$removedProfiles} profile and {$removedUsers} user(s) from router.",
                'removed_users' => $removedUsers,
                'removed_profiles' => $removedProfiles,
            ];
        } catch (Exception $e) {
            Log::error('Failed to delete package profile from router', [
                'router_id' => $router->id,
                'package_id' => $package->id,
                'profile_name' => $profileName,
                'error' => $e->getMessage(),
            ]);

            return [
                'success' => false,
                'message' => 'Failed to delete package profile: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * Create user on MikroTik
     */
    protected function createUser(Client $client, string $username, string $password, string $profileName, HotspotSession $session): void
    {
        // Remove existing user with same name (idempotent for reactivation/retry)
        $findQuery = (new Query('/ip/hotspot/user/print'))
            ->where('name', $username);
        $existing = $client->query($findQuery)->read();

        foreach ($existing as $user) {
            if (isset($user['.id'])) {
                $removeQuery = (new Query('/ip/hotspot/user/remove'))
                    ->equal('.id', $user['.id']);
                $client->query($removeQuery)->read();
            }
        }

        $expirationComment = $session->expires_at
            ? 'exp=' . $session->expires_at->format('M/d/Y H:i:s')
            : 'exp=none';

        if (!$session->expires_at || $session->expires_at <= now()) {
            Log::error('Creating hotspot user with expired session', [
                'session_id' => $session->session_id,
                'username' => $username,
                'expires_at' => $session->expires_at?->toIso8601String(),
                'created_at' => $session->created_at?->toDateTimeString(),
            ]);
        }

        $userData = [
            'name' => $username,
            'password' => $password,
            'profile' => $profileName,
            'comment' => $expirationComment,
        ];

        // Set limit-uptime (user-level usage limit) from package validity
        $limitUptime = $this->formatLimitUptime($session->package);
        if ($limitUptime) {
            $userData['limit-uptime'] = $limitUptime;
        }

        // Add MAC address binding if available
        if ($session->mac_address) {
            $userData['mac-address'] = $session->mac_address;
        }

        $query = new Query('/ip/hotspot/user/add');
        foreach ($userData as $key => $value) {
            $query->equal($key, $value);
        }

        $addResponse = $client->query($query)->read();

        // Check for !trap error in the response (RouterOS returns traps without throwing)
        if (isset($addResponse['after']['message'])) {
            throw new Exception("Router rejected user {$username}: " . $addResponse['after']['message']);
        }

        // Verify the user actually exists on the router
        $verifyQuery = (new Query('/ip/hotspot/user/print'))->where('name', $username);
        $verify = $client->query($verifyQuery)->read();

        if (empty($verify)) {
            throw new Exception("User creation failed: user {$username} was not found after creation.");
        }

        Log::info('Created hotspot user', [
            'username' => $username,
            'profile' => $profileName,
            'session_id' => $session->session_id,
            'limit_uptime' => $limitUptime ?: 'none',
            'expiration' => $session->expires_at?->toIso8601String(),
            'user_id' => $verify[0]['.id'] ?? null,
        ]);
    }

    /**
     * Remove active sessions from MikroTik
     */
    protected function removeActiveSessions(Client $client, HotspotSession $session): void
    {
        try {
            $username = $session->mikrotik_username ?: $session->username ?: $session->session_id;

            // Filter by username in the API query — avoids fetching all active sessions
            $query = (new Query('/ip/hotspot/active/print'))
                ->where('user', $username);
            $activeSessions = $client->query($query)->read();

            foreach ($activeSessions as $activeSession) {
                // Double-check match to avoid removing wrong user
                if ($this->isMatchingSession($activeSession, $session)) {
                    $removeQuery = (new Query('/ip/hotspot/active/remove'))
                        ->equal('.id', $activeSession['.id']);

                    $client->query($removeQuery)->read();

                    Log::info('Removed active hotspot session', [
                        'session_id' => $session->session_id,
                        'mikrotik_id' => $activeSession['.id']
                    ]);
                }
            }
            
        } catch (Exception $e) {
            Log::error('Failed to remove active sessions', [
                'session_id' => $session->session_id,
                'error' => $e->getMessage()
            ]);
        }
    }

    /**
     * Remove MAC cookies for a specific session's MAC address.
     * Only removes cookies matching this user's MAC — never removes all cookies.
     */
    protected function removeHotspotCookie(Client $client, HotspotSession $session): void
    {
        if (!$session->mac_address) {
            return;
        }

        try {
            $mac = strtolower($session->mac_address);

            $query = new Query('/ip/hotspot/cookie/print');
            $cookies = $client->query($query)->read();

            foreach ($cookies as $cookie) {
                $cookieMac = strtolower($cookie['mac-address'] ?? '');
                if ($cookieMac === $mac && isset($cookie['.id'])) {
                    $removeQuery = (new Query('/ip/hotspot/cookie/remove'))
                        ->equal('.id', $cookie['.id']);
                    $client->query($removeQuery)->read();

                    Log::info('Removed hotspot cookie for MAC', [
                        'session_id' => $session->session_id,
                        'mac_address' => $mac,
                    ]);
                }
            }
        } catch (Exception $e) {
            Log::warning('Failed to remove hotspot cookie', [
                'session_id' => $session->session_id,
                'mac_address' => $session->mac_address,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Remove user from MikroTik
     */
    protected function removeUser(Client $client, HotspotSession $session): void
    {
        try {
            $username = $session->mikrotik_username ?: $session->username ?: $session->session_id;
            
            $query = (new Query('/ip/hotspot/user/print'))
                ->where('name', $username);
            
            $users = $client->query($query)->read();
            
            foreach ($users as $user) {
                $removeQuery = (new Query('/ip/hotspot/user/remove'))
                    ->equal('.id', $user['.id']);
                
                $client->query($removeQuery)->read();
                
                Log::info('Removed hotspot user', [
                    'username' => $username,
                    'session_id' => $session->session_id
                ]);
            }
            
        } catch (Exception $e) {
            Log::error('Failed to remove hotspot user', [
                'session_id' => $session->session_id,
                'error' => $e->getMessage()
            ]);
        }
    }

    /**
     * Check if MikroTik session matches our session
     */
    protected function isMatchingSession(array $activeSession, HotspotSession $session): bool
    {
        // Match by username
        $username = $session->mikrotik_username ?: $session->username ?: $session->session_id;
        if (isset($activeSession['user']) && $activeSession['user'] === $username) {
            return true;
        }

        // Match by MAC address
        if ($session->mac_address && isset($activeSession['mac-address'])) {
            if (strtolower($session->mac_address) === strtolower($activeSession['mac-address'])) {
                return true;
            }
        }

        // Match by IP address
        if ($session->ip_address && isset($activeSession['address'])) {
            if ($session->ip_address === $activeSession['address']) {
                return true;
            }
        }

        return false;
    }

    /**
     * Format shared-users for MikroTik profile.
     * 0 or null = unlimited, 1 = omit (MikroTik default), >1 = explicit value.
     */
    protected function formatSharedUsers(?int $sharedUsers): string
    {
        if ($sharedUsers === null || $sharedUsers === 0) {
            return 'unlimited';
        }

        if ($sharedUsers === 1) {
            return ''; // MikroTik default is 1, no need to set explicitly
        }

        return (string) $sharedUsers;
    }

    /**
     * Parse MikroTik uptime string to seconds.
     * Handles formats: "1d2h3m4s", "1w2d3h4m5s", "37:59:59", "1:02:03:04"
     */
    protected function parseUptimeToSeconds(string $uptime): int
    {
        // Colon-delimited format: [days:]HH:MM:SS
        if (str_contains($uptime, ':')) {
            $parts = array_map('intval', explode(':', $uptime));
            if (count($parts) === 3) {
                return $parts[0] * 3600 + $parts[1] * 60 + $parts[2];
            }
            if (count($parts) === 4) {
                return $parts[0] * 86400 + $parts[1] * 3600 + $parts[2] * 60 + $parts[3];
            }
        }

        // Letter-suffix format: 1w2d3h4m5s
        $seconds = 0;
        $units = ['w' => 604800, 'd' => 86400, 'h' => 3600, 'm' => 60, 's' => 1];
        foreach ($units as $unit => $multiplier) {
            if (preg_match('/(\d+)' . $unit . '/i', $uptime, $matches)) {
                $seconds += (int) $matches[1] * $multiplier;
            }
        }

        return $seconds;
    }

    /**
     * Format rate limit for MikroTik
     */
    protected function formatRateLimit($package): string
    {
        $download = $package->bandwidth_download;
        $upload = $package->bandwidth_upload;

        if (!$download && !$upload) {
            return ''; // No rate limit = unlimited
        }

        // RouterOS hotspot user profile rate-limit format: rx/tx
        // Cast to int to avoid decimals like "4.00M" which RouterOS rejects
        $dl = $download ? (int) $download . 'M' : '0';
        $ul = $upload ? (int) $upload . 'M' : '0';

        return $ul . '/' . $dl;
    }

    /**
     * Parse data cap string (e.g., "1GB", "500MB") to bytes.
     * Returns null if no data cap or unparseable.
     */
    protected function parseDataCapToBytes(?string $dataCap): ?int
    {
        if (!$dataCap) {
            return null;
        }

        $dataCap = strtoupper(trim($dataCap));

        if (preg_match('/(\d+(?:\.\d+)?)\s*(GB|MB|KB)/', $dataCap, $matches)) {
            $value = floatval($matches[1]);
            $unit = $matches[2];

            switch ($unit) {
                case 'GB':
                    return (int) ($value * 1024 * 1024 * 1024);
                case 'MB':
                    return (int) ($value * 1024 * 1024);
                case 'KB':
                    return (int) ($value * 1024);
            }
        }

        return null;
    }

    /**
     * Format session timeout for MikroTik profile (HH:MM:SS)
     */
    protected function formatSessionTimeout($package): string
    {
        $seconds = $package->getSessionTimeoutSeconds();

        if ($seconds === null) {
            $seconds = 86400; // Default 24 hours
        }

        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds % 3600) / 60);
        $remainingSeconds = $seconds % 60;

        return sprintf('%02d:%02d:%02d', $hours, $minutes, $remainingSeconds);
    }

    /**
     * Format limit-uptime for MikroTik user (e.g. "1d", "2h", "1w", "4w2d").
     * This is a user-level usage limit, distinct from the profile-level session-timeout.
     */
    protected function formatLimitUptime($package): string
    {
        $seconds = $package->getSessionTimeoutSeconds();

        if ($seconds === null) {
            return '';
        }

        $weeks = floor($seconds / 604800);
        $seconds %= 604800;
        $days = floor($seconds / 86400);
        $seconds %= 86400;
        $hours = floor($seconds / 3600);
        $seconds %= 3600;
        $minutes = floor($seconds / 60);

        $parts = [];
        if ($weeks > 0) $parts[] = $weeks . 'w';
        if ($days > 0) $parts[] = $days . 'd';
        if ($hours > 0) $parts[] = $hours . 'h';
        if ($minutes > 0) $parts[] = $minutes . 'm';

        return implode('', $parts) ?: '1d';
    }

    /**
     * Generate random password
     */
    protected function generatePassword(): string
    {
        return bin2hex(random_bytes(8)); // 16 character hex password
    }


    /**
     * Get active user details from MikroTik
     */
    public function getActiveUserDetails(Router $router, string $username): ?array
    {
        try {
            $client = $this->connectToRouter($router);
            
            if (!$client) {
                return null;
            }

            // Get active session for the user
            $query = (new Query('/ip/hotspot/active/print'))
                ->where('user', $username);
            
            $activeSessions = $client->query($query)->read();
            
            if (empty($activeSessions)) {
                return null;
            }

            // Return the first matching session
            $session = $activeSessions[0];
            
            return [
                'username' => $session['user'] ?? $username,
                'address' => $session['address'] ?? null,
                'mac_address' => $session['mac-address'] ?? null,
                'uptime' => $session['uptime'] ?? '0s',
                'session_time_left' => $session['session-time-left'] ?? null,
                'idle_time' => $session['idle-time'] ?? '0s',
                'bytes_in' => $session['bytes-in'] ?? 0,
                'bytes_out' => $session['bytes-out'] ?? 0,
                'packets_in' => $session['packets-in'] ?? 0,
                'packets_out' => $session['packets-out'] ?? 0,
                'login_by' => $session['login-by'] ?? null,
            ];
            
        } catch (Exception $e) {
            Log::error('Failed to get active user details from MikroTik', [
                'router_id' => $router->id,
                'username' => $username,
                'error' => $e->getMessage()
            ]);
            
            return null;
        }
    }


    /**
     * Sync database sessions with router active sessions
     * - Creates missing sessions on router
     * - Marks sessions as expired if they don't exist on router anymore
     */
    public function syncSessionsWithRouter(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);
            
            if (!$client) {
                return [
                    'success' => false,
                    'message' => 'Cannot connect to router',
                    'synced' => 0,
                    'created' => 0,
                    'expired' => 0,
                ];
            }

            // Get all active sessions from router (includes byte counters)
            $query = new Query('/ip/hotspot/active/print');
            $routerSessions = $client->query($query)->read();

            // Get all hotspot users from router
            $userQuery = new Query('/ip/hotspot/user/print');
            $routerUsers = $client->query($userQuery)->read();

            // Create maps of router sessions (with data) and users
            $routerSessionMap = [];  // username => session data
            foreach ($routerSessions as $rs) {
                $user = $rs['user'] ?? null;
                $mac = strtolower($rs['mac-address'] ?? '');

                if ($user) {
                    $routerSessionMap[$user] = $rs;
                }
                if ($mac) {
                    $routerSessionMap[$mac] = $rs;
                }
            }

            $routerUserMap = [];
            foreach ($routerUsers as $ru) {
                $user = $ru['name'] ?? null;
                if ($user) {
                    $routerUserMap[$user] = true;
                }
            }

            // Get all active sessions from database for this router
            $dbSessions = HotspotSession::active()
                ->whereHas('package', function($q) use ($router) {
                    $q->where('router_id', $router->id);
                })
                ->get();

            $syncedCount = 0;
            $createdCount = 0;
            $expiredCount = 0;

            $missingCount = 0;

            foreach ($dbSessions as $session) {
                $username = $session->mikrotik_username ?: $session->username ?: $session->session_id;
                $mac = strtolower($session->mac_address ?: '');

                // Check if session exists on router (currently active)
                $routerSession = $routerSessionMap[$username] ?? ($mac ? ($routerSessionMap[$mac] ?? null) : null);
                $existsOnRouter = $routerSession !== null;

                // Check if user exists on router (even if not active)
                $userExistsOnRouter = isset($routerUserMap[$username]);

                if (!$userExistsOnRouter) {
                    // User missing on router — re-create via API (idempotent)
                    $missingCount++;
                    $recreated = $this->createHotspotSession($session);

                    Log::info('Session user missing on router, re-created via API', [
                        'session_id' => $session->session_id,
                        'username' => $username,
                        'recreated' => $recreated,
                    ]);
                } elseif ($existsOnRouter) {
                    // Session is active on router — update byte counters
                    $syncedCount++;

                    $uploadBytes = (int) ($routerSession['bytes-in'] ?? 0);
                    $downloadBytes = (int) ($routerSession['bytes-out'] ?? 0);
                    $uptime = $routerSession['uptime'] ?? null;

                    $updateData = [
                        'bytes_uploaded' => $uploadBytes,
                        'bytes_downloaded' => $downloadBytes,
                        'bytes_total' => $uploadBytes + $downloadBytes,
                    ];

                    if ($uptime) {
                        $data = $session->mikrotik_data ?? [];
                        $data['uptime_seconds'] = $this->parseUptimeToSeconds($uptime);
                        $data['last_synced_at'] = now()->toIso8601String();
                        $updateData['mikrotik_data'] = $data;
                    }

                    $session->update($updateData);
                } else {
                    // Session is NOT active on router — the user was
                    // disconnected by MikroTik (timeout, data limit, logout,
                    // admin kick, etc.) but our DB still shows it as active.
                    // Mark as 'disconnected' if time remains (user can
                    // reconnect), or 'expired' if time has run out.
                    //
                    // BUT: if the user has never connected (no bytes, no
                    // uptime), they may simply not have logged in through
                    // the captive portal yet. Don't expire them — the
                    // hotspot user still exists on the router and will
                    // work once they do log in.
                    $hasUsedData = ($session->bytes_total ?? 0) > 0
                        || !empty($session->mikrotik_data['uptime_seconds']);

                    if (!$hasUsedData) {
                        // User hasn't logged in yet — skip, don't expire
                        continue;
                    }

                    $stillValid = $session->expires_at && $session->expires_at > now();

                    $session->update([
                        'status' => $stillValid ? 'disconnected' : 'expired',
                        'expires_at' => $stillValid ? $session->expires_at : now(),
                    ]);

                    $expiredCount++;

                    Log::info('Sync: ' . ($stillValid ? 'disconnected' : 'expired') . ' stale session (not active on router)', [
                        'session_id' => $session->session_id,
                        'username' => $username,
                        'router_id' => $router->id,
                    ]);
                }
            }

            return [
                'success' => true,
                'message' => "Synced $syncedCount sessions, $missingCount re-created, $expiredCount expired",
                'synced' => $syncedCount,
                'created' => $createdCount,
                'missing' => $missingCount,
                'expired' => $expiredCount,
            ];
            
        } catch (Exception $e) {
            Log::error('Failed to sync sessions with router', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);
            
            return [
                'success' => false,
                'message' => 'Sync failed: ' . $e->getMessage(),
                'synced' => 0,
                'created' => 0,
                'expired' => 0,
            ];
        }
    }

    /**
     * Check whether a specific HotspotSession is still active on the router.
     * Used by getActiveSession() for on-demand verification.
     *
     * Returns true if the session is found in /ip/hotspot/active/print
     * (matched by username or MAC). Returns false if not found or on error.
     */
    public function isSessionActiveOnRouter(HotspotSession $session): bool
    {
        try {
            $router = $session->package?->router;

            if (!$router) {
                return false;
            }

            $client = $this->connectToRouter($router);

            if (!$client) {
                // Can't reach router — assume session is still active to
                // avoid falsely expiring sessions during network issues.
                return true;
            }

            $username = $session->mikrotik_username ?: $session->username ?: $session->session_id;
            $mac = strtolower($session->mac_address ?: '');

            // Filter by username — avoids fetching all active sessions on busy routers
            $query = (new Query('/ip/hotspot/active/print'))
                ->where('user', $username);
            $activeSessions = $client->query($query)->read();

            foreach ($activeSessions as $active) {
                $activeUser = $active['user'] ?? null;
                $activeMac = strtolower($active['mac-address'] ?? '');

                if ($activeUser && $activeUser === $username) {
                    return true;
                }
                if ($mac && $activeMac === $mac) {
                    return true;
                }
            }

            return false;

        } catch (Exception $e) {
            Log::warning('isSessionActiveOnRouter: error, assuming active', [
                'session_id' => $session->session_id,
                'error' => $e->getMessage(),
            ]);

            // On error, assume active to avoid false expiry
            return true;
        }
    }

    /**
     * Resolve the HotSpot gateway/server IP from already-fetched RouterOS
     * entries. This is the address MikroTik uses to build the `link-login`
     * URL when the HotSpot profile's dns-name is empty - it is intentionally
     * distinct from the router's management/API/WireGuard IP.
     *
     * Preference order:
     * 1. The HotSpot profile's `hotspot-address` property (explicit override).
     * 2. The IP address bound to the HotSpot's own interface.
     *
     * @param array|null $profileEntry Row from /ip/hotspot/profile/print for the hotspot's profile.
     * @param array|null $interfaceAddressEntry Row from /ip/address/print for the hotspot's interface.
     */
    public function resolveHotspotServerIp(?array $profileEntry, ?array $interfaceAddressEntry): ?string
    {
        $hotspotAddress = $profileEntry['hotspot-address'] ?? null;
        if (!empty($hotspotAddress)) {
            return explode('/', $hotspotAddress)[0];
        }

        $interfaceAddress = $interfaceAddressEntry['address'] ?? null;
        if (!empty($interfaceAddress)) {
            return explode('/', $interfaceAddress)[0];
        }

        return null;
    }

    /**
     * Test if hotspot service is enabled on router
     */
    public function testHotspotService(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);
            
            if (!$client) {
                return [
                    'success' => false,
                    'enabled' => false,
                    'message' => 'Cannot connect to router',
                    'interface' => null,
                    'server_ip' => null,
                ];
            }

            // Check if hotspot service is running
            $query = new Query('/ip/hotspot/print');
            $hotspotInfo = $client->query($query)->read();
            
            if (empty($hotspotInfo)) {
                return [
                    'success' => true,
                    'enabled' => false,
                    'message' => 'Hotspot service is not configured',
                    'interface' => null,
                    'server_ip' => null,
                ];
            }

            $hotspot = $hotspotInfo[0];
            $interface = $hotspot['interface'] ?? null;
            $profileName = $hotspot['profile'] ?? null;

            $profileEntry = null;
            if ($profileName) {
                $profileQuery = (new Query('/ip/hotspot/profile/print'))
                    ->where('name', $profileName);
                $profiles = $client->query($profileQuery)->read();
                $profileEntry = $profiles[0] ?? null;
            }

            $interfaceAddressEntry = null;
            if ($interface) {
                $addressQuery = (new Query('/ip/address/print'))
                    ->where('interface', $interface);
                $addresses = $client->query($addressQuery)->read();
                $interfaceAddressEntry = $addresses[0] ?? null;
            }

            $serverIp = $this->resolveHotspotServerIp($profileEntry, $interfaceAddressEntry ?: null);

            // RouterOS reports `hotspot-address=0.0.0.0` when the profile has no
            // explicit address configured. 0.0.0.0 can never be used to build
            // captive-portal handoff (link-login) URLs, so treat it as "not
            // detected" and warn the admin to configure the hotspot profile
            // with the router's LAN gateway IP.
            $serverIpWarning = null;
            if ($serverIp === null || $serverIp === '0.0.0.0') {
                $serverIp = null;
                $serverIpWarning = 'The hotspot profile has no valid hotspot-address configured. '
                    . 'Set it to the router\'s LAN gateway IP (the address clients reach the hotspot on), '
                    . 'as it is used to build captive-portal handoff links.';
            }

            return [
                'success' => true,
                'enabled' => true,
                'message' => 'Hotspot service is enabled',
                'interface' => $interface,
                'server_ip' => $serverIp,
                'server_ip_warning' => $serverIpWarning,
            ];
            
        } catch (Exception $e) {
            Log::error('Failed to test hotspot service', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);
            
            return [
                'success' => false,
                'enabled' => false,
                'message' => 'Error checking hotspot service: ' . $e->getMessage(),
                'interface' => null,
                'server_ip' => null,
            ];
        }
    }

    /**
     * Check walled garden status on router
     */
    public function checkWalledGardenStatus(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);
            
            if (!$client) {
                return [
                    'success' => false,
                    'configured' => false,
                    'domains' => [],
                    'ips' => [],
                    'message' => 'Cannot connect to router',
                ];
            }
            
            $apiHost = parse_url(rtrim(config('app.url'), '/'), PHP_URL_HOST);

            $domains = [];
            $ips = [];
            $hasApiHost = false;

            $hostEntries = $client->query(new Query('/ip/hotspot/walled-garden/print'))->read();
            foreach ($hostEntries as $entry) {
                if (!empty($entry['dst-host'])) {
                    $domains[] = $entry['dst-host'];
                    if ($apiHost && str_contains($entry['dst-host'], $apiHost)) {
                        $hasApiHost = true;
                    }
                }
            }

            $ipEntries = $client->query(new Query('/ip/hotspot/walled-garden/ip/print'))->read();
            foreach ($ipEntries as $entry) {
                if (!empty($entry['dst-address'])) {
                    $ips[] = $entry['dst-address'];
                }
            }
            
            $configured = !empty($domains) || !empty($ips);
            
            return [
                'success' => true,
                'configured' => $configured,
                'domains' => $domains,
                'ips' => $ips,
                'message' => $configured ? 'Walled garden configured' : 'Walled garden not configured',
            ];
        } catch (Exception $e) {
            Log::error('Failed to check walled garden status', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);
            
            return [
                'success' => false,
                'configured' => false,
                'domains' => [],
                'ips' => [],
                'message' => 'Error checking walled garden: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * Configure the router's hotspot server profile to serve the local hotspot
     * files (login.html, status.html, etc.) instead of redirecting to an external
     * captive portal. Ensures http-login-page is cleared so RouterOS uses the
     * local HTML directory, and adds the Laravel app + Google Fonts to the
     * walled garden so the local page can call the API at runtime.
     */
    public function configureLocalPortal(Router $router, string $apiBaseUrl): array
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return ['success' => false, 'message' => 'Cannot connect to router'];
            }

            $profileQuery = new Query('/ip/hotspot/profile/print');
            $profiles = $client->query($profileQuery)->read();

            foreach ($profiles as $profile) {
                if (isset($profile['.id'])) {
                    $setQuery = new Query('/ip/hotspot/profile/set');
                    $setQuery->equal('.id', $profile['.id']);
                    // Use both CHAP and PAP so login.html can do either path,
                    // plus mac-cookie for seamless reconnects.
                    $setQuery->equal('login-by', 'http-pap,http-chap,mac-cookie');
                    // Serve the local login.html from the hotspot html directory.
                    $setQuery->equal('html-directory', 'hotspot');
                    $setQuery->equal('split-user-domain', 'no');
                    // Force local user authentication; disable any legacy RADIUS config.
                    $setQuery->equal('use-radius', 'no');
                    $setQuery->equal('radius-accounting', 'no');
                    $client->query($setQuery)->read();
                }
            }

            $apiHost = parse_url($apiBaseUrl, PHP_URL_HOST);
            $walledGardenHosts = array_filter([
                $apiHost,
                'fonts.googleapis.com',
                'fonts.gstatic.com',
                'connectivitycheck.gstatic.com',
                'captive.apple.com',
                'www.msftconnecttest.com',
                'detectportal.firefox.com',
            ]);

            foreach ($walledGardenHosts as $host) {
                if (!$host) {
                    continue;
                }
                $existingQuery = new Query('/ip/hotspot/walled-garden/print');
                $existingQuery->where('dst-host', $host);
                $existingEntries = $client->query($existingQuery)->read();

                if (empty($existingEntries)) {
                    $addGardenQuery = new Query('/ip/hotspot/walled-garden/add');
                    $addGardenQuery->equal('dst-host', $host);
                    $response = $client->query($addGardenQuery)->read();

                    if ($this->responseHasError($response)) {
                        throw new Exception("Router rejected walled garden host {$host}: " . $this->responseErrorMessage($response));
                    }
                }
            }

            Log::info('Local portal configured on router', [
                'router_id' => $router->id,
                'api_base_url' => $apiBaseUrl,
            ]);

            return ['success' => true, 'message' => 'Router configured to use local hotspot files'];

        } catch (Exception $e) {
            Log::error('Failed to configure external portal', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);

            return ['success' => false, 'message' => 'Portal configuration failed: ' . $e->getMessage()];
        }
    }

    /**
     * One-click hotspot setup for a router.
     *
     * Creates/updates a local hotspot user profile, ensures a HotSpot server
     * is running on the configured interface, and applies the local portal
     * configuration + walled garden entries.
     */
    public function setupHotspot(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return ['success' => false, 'message' => 'Cannot connect to router'];
            }

            $interface = $router->hotspot_interface;

            if (!$interface) {
                return [
                    'success' => false,
                    'message' => 'No hotspot interface configured. Sync HotSpot Gateway IP first.',
                ];
            }

            $serverProfileName = 'hotspot-local';

            // Ensure the hotspot SERVER profile exists and uses local authentication.
            // This is NOT a user profile; it controls login methods, RADIUS, and the portal page.
            $serverProfileQuery = (new Query('/ip/hotspot/profile/print'))
                ->where('name', $serverProfileName);
            $serverProfiles = $client->query($serverProfileQuery)->read();

            $serverProfileData = [
                'login-by' => 'http-pap,http-chap,mac-cookie',
                'html-directory' => 'hotspot',
                'split-user-domain' => 'no',
                'use-radius' => 'no',
                'radius-accounting' => 'no',
            ];

            if (empty($serverProfiles)) {
                $addServerProfile = new Query('/ip/hotspot/profile/add');
                $addServerProfile->equal('name', $serverProfileName);
                foreach ($serverProfileData as $key => $value) {
                    $addServerProfile->equal($key, $value);
                }
                $client->query($addServerProfile)->read();
                Log::info('Created hotspot server profile', ['router_id' => $router->id, 'profile' => $serverProfileName]);
            } else {
                $setServerProfile = new Query('/ip/hotspot/profile/set');
                $setServerProfile->equal('.id', $serverProfiles[0]['.id']);
                foreach ($serverProfileData as $key => $value) {
                    $setServerProfile->equal($key, $value);
                }
                $client->query($setServerProfile)->read();
                Log::info('Updated hotspot server profile', ['router_id' => $router->id, 'profile' => $serverProfileName]);
            }

            // Ensure the hotspot server exists on the chosen interface and uses the local profile
            $serverQuery = (new Query('/ip/hotspot/print'))
                ->where('name', 'hotspot1');
            $servers = $client->query($serverQuery)->read();

            if (empty($servers)) {
                $addServer = new Query('/ip/hotspot/add');
                $addServer->equal('name', 'hotspot1');
                $addServer->equal('interface', $interface);
                $addServer->equal('profile', $serverProfileName);
                $addServer->equal('addresses-per-mac', '2');
                $addServer->equal('address-pool', 'none');
                $client->query($addServer)->read();
                Log::info('Created hotspot server', ['router_id' => $router->id, 'interface' => $interface]);
            } else {
                $setServer = new Query('/ip/hotspot/set');
                $setServer->equal('.id', $servers[0]['.id']);
                $setServer->equal('interface', $interface);
                $setServer->equal('profile', $serverProfileName);
                $client->query($setServer)->read();
                Log::info('Updated hotspot server', ['router_id' => $router->id, 'interface' => $interface]);
            }

            // Apply local portal profile settings and walled garden entries
            $apiBaseUrl = rtrim(config('app.url'), '/');
            $portalResult = $this->configureLocalPortal($router, $apiBaseUrl);

            if (!$portalResult['success']) {
                return [
                    'success' => false,
                    'message' => 'Hotspot server created, but local portal config failed: ' . ($portalResult['message'] ?? 'unknown error'),
                ];
            }

            return [
                'success' => true,
                'message' => 'Hotspot server and local portal configured successfully',
            ];

        } catch (Exception $e) {
            Log::error('Failed to set up hotspot', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);

            return ['success' => false, 'message' => 'Hotspot setup failed: ' . $e->getMessage()];
        }
    }

    /**
     * Sync all active package profiles for a router to RouterOS.
     *
     * Creates or updates hotspot user profiles for each active package,
     * then updates the router's sync counters. This lets admins push
     * package changes to the router before any session is created.
     */
    public function syncPackageProfiles(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return [
                    'success' => false,
                    'message' => 'Could not connect to router',
                ];
            }

            $packages = Package::where('router_id', $router->id)
                ->where('is_active', true)
                ->get();

            Log::info('Syncing package profiles', [
                'router_id' => $router->id,
                'package_count' => $packages->count(),
            ]);

            if ($packages->isEmpty()) {
                return [
                    'success' => false,
                    'message' => 'No active packages found for this router. Create and activate packages first.',
                ];
            }

            $synced = 0;
            $failed = 0;
            $errors = [];

            foreach ($packages as $package) {
                try {
                    $this->syncPackageProfile($client, $package);
                    $synced++;
                } catch (Exception $e) {
                    $failed++;
                    $errors[] = "pkg_{$package->id}: {$e->getMessage()}";
                    Log::error('Failed to sync package profile', [
                        'router_id' => $router->id,
                        'package_id' => $package->id,
                        'error' => $e->getMessage(),
                    ]);
                }
            }

            $router->update([
                'packages_sync_count' => $synced,
                'packages_unsync_count' => $packages->count() - $synced,
                'last_synced_at' => now(),
            ]);

            if ($failed > 0) {
                return [
                    'success' => false,
                    'message' => "Synced {$synced} profiles, {$failed} failed: " . implode('; ', $errors),
                    'synced' => $synced,
                    'failed' => $failed,
                ];
            }

            return [
                'success' => true,
                'message' => "Synced {$synced} package profile(s) successfully.",
                'synced' => $synced,
                'failed' => $failed,
            ];
        } catch (Exception $e) {
            Log::error('Failed to sync package profiles', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);

            return [
                'success' => false,
                'message' => 'Package profile sync failed: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * Apply walled garden settings to router (idempotent).
     * Adds missing entries and removes entries no longer in the desired list.
     * Does NOT remove entries that were added by other means (e.g. configureLocalPortal).
     */
    public function applyWalledGarden(Router $router, array $domains, array $ips): bool
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return false;
            }

            // Get existing walled garden entries from both host and IP menus
            $existingDomains = [];
            $existingIps = [];

            $hostEntries = $client->query(new Query('/ip/hotspot/walled-garden/print'))->read();
            foreach ($hostEntries as $entry) {
                if (!empty($entry['dst-host'])) {
                    $existingDomains[$entry['dst-host']] = $entry['.id'] ?? null;
                }
            }

            $ipEntries = $client->query(new Query('/ip/hotspot/walled-garden/ip/print'))->read();
            foreach ($ipEntries as $entry) {
                if (!empty($entry['dst-address'])) {
                    $existingIps[$entry['dst-address']] = $entry['.id'] ?? null;
                }
            }

            $desiredDomains = array_values(array_filter($domains, fn($d) => !empty($d)));
            $desiredIps = array_values(array_filter($ips, fn($i) => !empty($i)));

            $addedDomains = 0;
            $addedIps = 0;
            $errors = [];

            // Add missing domain entries
            foreach ($desiredDomains as $domain) {
                if (isset($existingDomains[$domain])) {
                    continue;
                }

                $addQuery = new Query('/ip/hotspot/walled-garden/add');
                $addQuery->equal('dst-host', $domain);
                $response = $client->query($addQuery)->read();

                if ($this->responseHasError($response)) {
                    $errors[] = "Failed to add domain {$domain}: " . $this->responseErrorMessage($response);
                    continue;
                }

                $addedDomains++;
            }

            // Add missing IP entries under the dedicated IP walled-garden menu
            foreach ($desiredIps as $ip) {
                if (isset($existingIps[$ip])) {
                    continue;
                }

                $addQuery = new Query('/ip/hotspot/walled-garden/ip/add');
                $addQuery->equal('dst-address', $ip);
                $response = $client->query($addQuery)->read();

                if ($this->responseHasError($response)) {
                    $errors[] = "Failed to add IP {$ip}: " . $this->responseErrorMessage($response);
                    continue;
                }

                $addedIps++;
            }

            // Verify entries were actually persisted
            $verifyDomains = $client->query(new Query('/ip/hotspot/walled-garden/print'))->read();
            $verifyIps = $client->query(new Query('/ip/hotspot/walled-garden/ip/print'))->read();
            $persistedDomains = array_filter(array_column($verifyDomains, 'dst-host'));
            $persistedIps = array_filter(array_column($verifyIps, 'dst-address'));
            $missingDomains = array_diff($desiredDomains, $persistedDomains);
            $missingIps = array_diff($desiredIps, $persistedIps);

            if (!empty($missingDomains) || !empty($missingIps)) {
                $errors[] = 'Entries missing after apply. Missing domains: ' . implode(', ', $missingDomains) .
                            '; Missing IPs: ' . implode(', ', $missingIps);
            }

            if (!empty($errors)) {
                throw new Exception(implode(' | ', $errors));
            }

            Log::info('Walled garden applied to router (idempotent)', [
                'router_id' => $router->id,
                'domains_count' => count($desiredDomains),
                'ips_count' => count($desiredIps),
                'domains_added' => $addedDomains,
                'ips_added' => $addedIps,
            ]);

            return true;

        } catch (Exception $e) {
            Log::error('Failed to apply walled garden to router', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);

            return false;
        }
    }

    /**
     * Determine whether a RouterOS API response contains an error/trap.
     */
    private function responseHasError($response): bool
    {
        if (!is_array($response) || empty($response)) {
            return true;
        }

        if (isset($response['after']['message'])) {
            return true;
        }

        foreach ($response as $item) {
            if (is_array($item) && (isset($item['message']) || isset($item['after']['message']))) {
                return true;
            }
        }

        return false;
    }

    /**
     * Extract the error message from a RouterOS API response.
     */
    private function responseErrorMessage($response): string
    {
        if (!is_array($response)) {
            return 'Invalid response from router';
        }

        if (isset($response['after']['message'])) {
            return $response['after']['message'];
        }

        foreach ($response as $item) {
            if (is_array($item)) {
                if (isset($item['after']['message'])) {
                    return $item['after']['message'];
                }
                if (isset($item['message'])) {
                    return $item['message'];
                }
            }
        }

        return 'Unknown router API error';
    }

    /**
     * Get router setup checklist — checks each setup step and returns
     * whether it's done, plus a label and description for each item.
     */
    public function getSetupChecklist(Router $router): array
    {
        $steps = [
            [
                'key' => 'connection',
                'label' => 'Router Connection',
                'description' => 'API is reachable and credentials work',
                'done' => false,
                'action_route' => 'test-connection',
                'action_method' => 'POST',
            ],
            [
                'key' => 'hotspot_interface',
                'label' => 'Sync Hotspot Gateway IP',
                'description' => 'Detect the hotspot interface and server IP',
                'done' => false,
                'action_route' => 'sync-hotspot-info',
                'action_method' => 'POST',
            ],
            [
                'key' => 'hotspot_setup',
                'label' => 'Setup Hotspot Server',
                'description' => 'Create hotspot server, profile, and local portal config',
                'done' => false,
                'action_route' => 'setup-hotspot',
                'action_method' => 'POST',
            ],
            [
                'key' => 'package_profiles',
                'label' => 'Sync Package Profiles',
                'description' => 'Push package rate limits and data caps to router',
                'done' => false,
                'action_route' => 'sync-package-profiles',
                'action_method' => 'POST',
            ],
            [
                'key' => 'hotspot_files',
                'label' => 'Upload Hotspot Files',
                'description' => 'Upload login.html and assets to router',
                'done' => false,
                'action_route' => 'upload-hotspot-files',
                'action_method' => 'POST',
            ],
            [
                'key' => 'walled_garden',
                'label' => 'Apply Walled Garden',
                'description' => 'Allow API, fonts, and OS connectivity checks through captive portal',
                'done' => false,
                'action_route' => 'apply-walled-garden',
                'action_method' => 'POST',
            ],
        ];

        try {
            $client = $this->connectToRouter($router);

            // Step 1: Connection
            $steps[0]['done'] = $client !== null;

            if (!$client) {
                return ['steps' => $steps, 'reachable' => false];
            }

            // Step 2: Hotspot interface — check if router has hotspot_interface set
            $steps[1]['done'] = !empty($router->hotspot_interface);

            // Step 3: Hotspot setup — check if hotspot server exists
            $serverQuery = new Query('/ip/hotspot/print');
            $servers = $client->query($serverQuery)->read();
            $steps[2]['done'] = !empty($servers);

            // Step 4: Package profiles — check if any user profiles exist
            $profileQuery = new Query('/ip/hotspot/user/profile/print');
            $profiles = $client->query($profileQuery)->read();
            $steps[3]['done'] = !empty($profiles);

            // Step 5: Hotspot files — check if login.html exists on router
            $hasFiles = false;
            if (!empty($servers)) {
                $profileName = $servers[0]['profile'] ?? 'hotspot-local';
                $spQuery = (new Query('/ip/hotspot/profile/print'))->where('name', $profileName);
                $sp = $client->query($spQuery)->read();
                if (!empty($sp) && isset($sp[0]['html-directory'])) {
                    $fileQuery = new Query('/file/print');
                    $fileQuery->where('name', 'hotspot/login.html');
                    $files = $client->query($fileQuery)->read();
                    $hasFiles = !empty($files);
                }
            }
            $steps[4]['done'] = $hasFiles;

            // Step 6: Walled garden — check if essential domains are present
            $wgQuery = new Query('/ip/hotspot/walled-garden/print');
            $wgEntries = $client->query($wgQuery)->read();
            $wgDomains = [];
            foreach ($wgEntries as $entry) {
                if (isset($entry['dst-host']) && ($entry['action'] ?? '') === 'accept') {
                    $wgDomains[] = $entry['dst-host'];
                }
            }
            $apiHost = parse_url(rtrim(config('app.url'), '/'), PHP_URL_HOST);
            $requiredDomains = array_filter([
                $apiHost,
                'connectivitycheck.gstatic.com',
                'captive.apple.com',
                'www.msftconnecttest.com',
                'detectportal.firefox.com',
            ]);
            $missingDomains = array_filter($requiredDomains, fn($d) => !in_array($d, $wgDomains));
            $steps[5]['done'] = empty($missingDomains);

            return ['steps' => $steps, 'reachable' => true];

        } catch (\Exception $e) {
            Log::error('Failed to get setup checklist', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);
            return ['steps' => $steps, 'reachable' => false];
        }
    }

    /**
     * Get comprehensive router diagnostics
     */
    public function getRouterDiagnostics(Router $router): array
    {
        try {
            $connection = $this->testConnection($router);
            $hotspot = $this->testHotspotService($router);
            $walledGarden = $this->checkWalledGardenStatus($router);
            
            // Get package sync status
            $totalPackages = \App\Models\Package::where('router_id', $router->id)->count();
            $syncedCount = $router->packages_sync_count ?? 0;
            $unsyncCount = $router->packages_unsync_count ?? 0;
            
            $lastSyncedAt = $router->last_synced_at;
            if ($lastSyncedAt && is_string($lastSyncedAt)) {
                $lastSyncedAt = \Carbon\Carbon::parse($lastSyncedAt)->format('Y-m-d H:i:s');
            } elseif ($lastSyncedAt) {
                $lastSyncedAt = $lastSyncedAt->format('Y-m-d H:i:s');
            }
            
            return [
                'connection' => $connection,
                'hotspot' => $hotspot,
                'walled_garden' => $walledGarden,
                'sync' => [
                    'total' => $totalPackages,
                    'synced' => $syncedCount,
                    'unsynced' => $unsyncCount,
                    'last_synced_at' => $lastSyncedAt,
                ],
            ];
        } catch (\Exception $e) {
            \Log::error('Get router diagnostics failed', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            
            return [
                'connection' => [
                    'success' => false,
                    'message' => 'Diagnostics failed: ' . $e->getMessage(),
                    'diagnostics' => [
                        'api_port' => false,
                        'http_port' => false,
                        'https_port' => false,
                    ]
                ],
                'hotspot' => null,
                'walled_garden' => null,
                'sync' => null,
            ];
        }
    }

    /**
     * Reboot the router
     */
    public function rebootRouter(Router $router): array
    {
        try {
            $client = new Client([
                "host" => $router->ip,
                "user" => $router->username,
                "pass" => $router->password,
            ]);

            // Trigger a router reboot
            $query = (new Query('/system/reboot'));
            $client->query($query)->read();

            return [
                'success' => true,
                'message' => 'Router reboot initiated'
            ];
        } catch (\Exception $e) {
            \Log::error('Router reboot failed', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);
            return [
                'success' => false,
                'message' => 'Failed to reboot router: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Backup the router configuration
     */
    public function backupRouter(Router $router): array
    {
        try {
            $client = new Client([
                "host" => $router->ip,
                "user" => $router->username,
                "pass" => $router->password,
            ]);

            // Save a backup file on the router's local storage
            $query = (new Query('/system/backup/save'));
            $client->query($query)->read();

            return [
                'success' => true,
                'message' => 'Backup created successfully',
                'backup_file' => 'backup.backup'
            ];
        } catch (\Exception $e) {
            \Log::error('Router backup failed', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);
            return [
                'success' => false,
                'message' => 'Failed to backup router: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Get router configuration
     */
    public function getRouterConfig(Router $router): array
    {
        try {
            $client = new Client([
                "host" => $router->ip,
                "user" => $router->username,
                "pass" => $router->password,
            ]);

            // Pull basic system/resource info for the configuration export
            $query = (new Query('/system/resource/print'));
            $result = $client->query($query)->read();

            $config = "# Router Configuration Export\n";
            $config .= "# Router: " . $router->name . "\n";
            $config .= "# IP: " . $router->ip . "\n";
            $config .= "# Generated: " . now()->format('Y-m-d H:i:s') . "\n\n";
            
            if (!empty($result)) {
                $config .= "# System Resources:\n";
                foreach ($result[0] as $key => $value) {
                    if ($key !== '.tag') {
                        $config .= "# {$key}: {$value}\n";
                    }
                }
            }

            return [
                'success' => true,
                'config' => $config
            ];
        } catch (\Exception $e) {
            \Log::error('Get router config failed', [
                'router_id' => $router->id,
                'error' => $e->getMessage()
            ]);
            return [
                'success' => false,
                'message' => 'Failed to get config: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Get interface traffic stats (RX/TX bytes per interface)
     */
    public function getInterfaceTraffic(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return ['success' => false, 'message' => 'Cannot connect to router'];
            }

            $query = new Query('/interface/print');
            $query->equal('stats-detail', 'minute');
            $response = $client->query($query)->read();

            $interfaces = [];
            foreach ($response as $iface) {
                $rxBytes = (int) ($iface['rx-byte'] ?? 0);
                $txBytes = (int) ($iface['tx-byte'] ?? 0);
                $rxRate = (float) ($iface['rx-rate'] ?? 0);
                $txRate = (float) ($iface['tx-rate'] ?? 0);

                $interfaces[] = [
                    'name' => $iface['name'] ?? 'unknown',
                    'type' => $iface['type'] ?? 'unknown',
                    'running' => ($iface['running'] ?? 'false') === 'true',
                    'disabled' => ($iface['disabled'] ?? 'false') === 'true',
                    'rx_bytes' => $rxBytes,
                    'tx_bytes' => $txBytes,
                    'rx_rate' => $rxRate,
                    'tx_rate' => $txRate,
                    'rx_rate_mbps' => round($rxRate / 1000000, 2),
                    'tx_rate_mbps' => round($txRate / 1000000, 2),
                ];
            }

            return [
                'success' => true,
                'interfaces' => $interfaces,
            ];
        } catch (Exception $e) {
            Log::error('Failed to get interface traffic', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);
            return ['success' => false, 'message' => 'Failed to get traffic: ' . $e->getMessage()];
        }
    }

    /**
     * Get router health metrics (CPU, memory, uptime)
     */
    public function getRouterHealth(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return ['success' => false, 'message' => 'Cannot connect to router'];
            }

            $query = new Query('/system/resource/print');
            $response = $client->query($query)->read();

            if (empty($response)) {
                return ['success' => false, 'message' => 'No resource data received'];
            }

            $data = $response[0];

            $memoryTotal = (int) ($data['total-memory'] ?? 0);
            $memoryUsed = (int) ($data['free-memory'] ?? 0);
            $memoryUsed = $memoryTotal - $memoryUsed;

            return [
                'success' => true,
                'cpu_load' => (int) ($data['cpu-load'] ?? 0),
                'memory_total' => $memoryTotal,
                'memory_used' => $memoryUsed,
                'memory_percentage' => $memoryTotal > 0 ? round(($memoryUsed / $memoryTotal) * 100, 1) : 0,
                'uptime' => $data['uptime'] ?? '0s',
                'uptime_seconds' => $this->parseUptimeToSeconds($data['uptime'] ?? '0s'),
                'version' => $data['version'] ?? 'unknown',
                'board_name' => $data['board-name'] ?? 'unknown',
                'architecture' => $data['architecture'] ?? 'unknown',
            ];
        } catch (Exception $e) {
            Log::error('Failed to get router health', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);
            return ['success' => false, 'message' => 'Failed to get health: ' . $e->getMessage()];
        }
    }

    /**
     * Upload hotspot HTML files to the router's hotspot directory via the API.
     * Uses HotspotFileGeneratorService to produce per-router content, then
     * writes each file via /file/set with contents.
     */
    public function uploadHotspotFiles(Router $router): array
    {
        try {
            $client = $this->connectToRouter($router);

            if (!$client) {
                return ['success' => false, 'message' => 'Cannot connect to router'];
            }

            $setting = \App\Models\Setting::first();
            $companyName = $setting?->company_name ?: config('app.name', 'Hotspot');
            $supportPhone = $setting?->support_phone ?: '';
            $currency = $setting?->currency ?: 'KSH';

            $replacements = [
                '{RouterIdentifier}' => $router->identifier,
                '{PortalUrl}' => rtrim(config('app.url'), '/'),
                '{Company}' => $companyName,
                '{CompanyName}' => $companyName,
                '{ApiBaseUrl}' => rtrim(config('app.url'), '/'),
                '{SupportPhone}' => $supportPhone,
                '{Currency}' => $currency,
            ];

            $templateDir = base_path('hotspot_router_files/hotspot');
            $uploaded = 0;
            $errors = [];

            $this->uploadDirectoryFiles($client, $templateDir, 'hotspot', $replacements, $uploaded, $errors);

            if (!empty($errors)) {
                return [
                    'success' => false,
                    'message' => 'Uploaded ' . $uploaded . ' files, but errors occurred: ' . implode('; ', array_slice($errors, 0, 5)),
                ];
            }

            Log::info('Hotspot files uploaded to router', [
                'router_id' => $router->id,
                'files_uploaded' => $uploaded,
            ]);

            return [
                'success' => true,
                'message' => 'Uploaded ' . $uploaded . ' hotspot files to router',
            ];
        } catch (Exception $e) {
            Log::error('Failed to upload hotspot files', [
                'router_id' => $router->id,
                'error' => $e->getMessage(),
            ]);
            return ['success' => false, 'message' => 'Upload failed: ' . $e->getMessage()];
        }
    }

    /**
     * Recursively upload files from a local directory to the router.
     * Text files (html, css, js, txt, json) get placeholder substitution.
     * Binary files (ico, png, woff2) are skipped — they must be uploaded manually via FTP/WinBox.
     */
    private function uploadDirectoryFiles(Client $client, string $sourceDir, string $remotePath, array $replacements, int &$uploaded, array &$errors): void
    {
        foreach (scandir($sourceDir) as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $sourcePath = $sourceDir . DIRECTORY_SEPARATOR . $item;
            $remoteFilePath = $remotePath . '/' . $item;

            if (is_dir($sourcePath)) {
                $this->uploadDirectoryFiles($client, $sourcePath, $remoteFilePath, $replacements, $uploaded, $errors);
                continue;
            }

            $extension = strtolower(pathinfo($item, PATHINFO_EXTENSION));

            // Only upload text files via API; binary files need FTP/WinBox
            if (!in_array($extension, ['html', 'css', 'js', 'txt', 'json'], true)) {
                continue;
            }

            $contents = file_get_contents($sourcePath);
            $contents = strtr($contents, $replacements);

            try {
                // Check if file already exists
                $printQuery = new Query('/file/print');
                $printQuery->where('name', $remoteFilePath);
                $existing = $client->query($printQuery)->read();

                if (!empty($existing)) {
                    // Update existing file
                    $setQuery = new Query('/file/set');
                    $setQuery->equal('.id', $existing[0]['.id']);
                    $setQuery->equal('contents', $contents);
                    $client->query($setQuery)->read();
                } else {
                    // Create new file
                    $addQuery = new Query('/file/add');
                    $addQuery->equal('name', $remoteFilePath);
                    $addQuery->equal('contents', $contents);
                    $client->query($addQuery)->read();
                }

                $uploaded++;
            } catch (Exception $e) {
                $errors[] = $remoteFilePath . ': ' . $e->getMessage();
                Log::warning('Failed to upload file to router', [
                    'file' => $remoteFilePath,
                    'error' => $e->getMessage(),
                ]);
            }
        }
    }
}
